default: &default
 adapter: postgresql
 encoding: unicode
 host: localhost #postgres://xqndcwcxncdymd:s5qm1oIwEDcr #localhost
 pool: 5
 database: <%= ENV["POSTGRESQL_DATABASE"] %>
 username: <%= ENV["POSTGRESQL_USERNAME"] %>
 password: <%= ENV['POSTGRESQL_PASSWORD'] %>

development:
 <<: *default

staging:
 <<: *default

test:
 <<: *default
 database: alumaster_test

production:
  <<: *default