default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost #postgres://xqndcwcxncdymd:s5qm1oIwEDcr #localhost
  pool: 5
  username: postgres #<%= ENV["POSTGRESQL_USERNAME"] %>
  password: postgres #<%= ENV['POSTGRESQL_PASSWORD'] %>
  database: alumaster_db #<%= ENV["POSTGRESQL_DATABASE"] %>

development:
  <<: *default

staging:
  <<: *default

test:
  <<: *default
  database: alumaster_test

#production:
#  <<: *default